import turtle
turtle.setup(800,800)
window=turtle.Screen()
window.title('My first turtle program')
window=turtle.Screen()
window.bgcolor('red')
window=turtle.Screen()
window.title('absolute positioning')
the_turtle=turtle.getturtle()
the_turtle.hideturtle()
the_turtle.pensize(15)
the_turtle.setposition(100,0)
the_turtle.setposition(100,0)
the_turtle.setposition(0,100)
the_turtle.setposition(0,0)
